# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_grade_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='grade_date',
            new_name='rating_date',
        ),
    ]
